// All site copy in one place. EN + ES.
export type Lang = 'en' | 'es'

export interface Metric { label: string; value: string }
export interface Project {
  name: string
  tag: string
  year: string
  description: string
  link: string
  tech: string[]
  metrics?: Metric[]
  featured?: boolean
  span?: 'wide'
  /** Slug for /demos/<slug>.{mp4,jpg} — when set, card renders an autoplaying muted loop with poster fallback */
  media?: string
  /** Ordered pipeline steps, rendered as a dot-and-line flow diagram in the card. */
  pipeline?: string[]
}
export interface ExperienceItem {
  company: string
  role: string
  period: string
  note: string
}
export interface PressItem {
  date: string
  outlet: string
  title: string
  link?: string
}

export interface Content {
  meta: {
    title: string
    description: string
  }
  nav: {
    en: string
    es: string
    work: string
    writing: string
    about: string
    hire: string
  }
  skipToContent: string
  mobileDock: { resume: string; hire: string }
  hero: {
    display: { lead: string; em: string; tail: string }
    lede: React.ReactNode | string
    metaItems: { key: string; val: string }[]
  }
  workUi: {
    evidence: string
    archiveTitle: string
    archiveBody: string
    openProject: string
  }
  /** Hard numbers strip under the hero. */
  proofBar: { value: string; label: string }[]
  /** Claim → evidence rows for the stack section. */
  stackProof: { claim: string; evidence: string }[]
  sections: {
    work: string
    writing: string
    press: string
    now: string
    experience: string
    proof: string
    available: string
    connect: string
  }
  projects: Project[]
  experience: ExperienceItem[]
  press: PressItem[]
  pressEmptyHint: string
  now: { headline: string; lines: string[]; updated: string }
  available: {
    headline: { lead: string; em: string; tail: string }
    body: string
    channels: {
      key: string
      title: string
      desc: string
      cta: string
      href: string
    }[]
    aside: { key: string; val: string }[]
  }
  writingCta: string
  allWriting: string
  footer: string
}

export const content: Record<Lang, Content> = {
  en: {
    meta: {
      title: 'Jan Faris — AI products from Puerto Rico',
      description:
        'Software engineer building Spanish-first AI products from Puerto Rico. Ex-Microsoft. Creator of Lupa, demotape, and usableai.',
    },
    nav: {
      en: 'EN',
      es: 'ES',
      work: 'Work',
      writing: 'Writing',
      about: 'About',
      hire: 'Hire',
    },
    skipToContent: 'Skip to content',
    mobileDock: { resume: 'Résumé', hire: 'Hire Jan' },
    hero: {
      display: { lead: 'Software, ', em: 'shipped', tail: '.' },
      lede:
        'AI product engineer for agents, developer tools, and Spanish-first products. Ex-Microsoft. I build and ship end to end.',
      metaItems: [
        { key: 'status', val: 'open to work · ex-SWE II @ Microsoft' },
        { key: 'shipped', val: '2 npm, 1 App Store, internal tools' },
        { key: 'languages', val: 'EN · ES' },
      ],
    },
    workUi: {
      evidence: 'Project evidence',
      archiveTitle: 'More shipped work',
      archiveBody: 'Smaller products and experiments, kept concise for a faster scan.',
      openProject: 'Open project',
    },
    proofBar: [
      { value: '08', label: 'products shipped' },
      { value: '2 npm · 1 App Store', label: 'public launches' },
      { value: '5.0 / 5.0', label: 'Microsoft internal AI eval (PRPilot)' },
      { value: '120+', label: 'demo sites generated by Lupa' },
    ],
    stackProof: [
      {
        claim: 'TypeScript / Node',
        evidence: '2 published npm packages: demotape and spanish-tone-spec, both MIT.',
      },
      {
        claim: 'LLM systems',
        evidence: 'PRPilot scored 5.0/5.0 on Microsoft internal AI evaluations across 7+ repos.',
      },
      {
        claim: 'Spanish-first AI',
        evidence: 'usableai publishes to Instagram daily: RSS to carousel, fully automated.',
      },
      {
        claim: 'Full-stack product',
        evidence: 'Janga live on the App Store. Lupa has generated 120+ personalized client demo sites.',
      },
      {
        claim: 'Production scale',
        evidence: 'Commerce Core at Microsoft. Led the Snowflake migration at Xtillion.',
      },
    ],
    sections: {
      work: 'Selected Work',
      writing: 'Writing',
      press: 'Press & Speaking',
      now: 'Currently Building',
      experience: 'Experience',
      proof: 'Stack, Proven',
      available: 'Work With Me',
      connect: 'Connect',
    },
    projects: [
      {
        name: 'Lupa',
        media: 'lupa',
        tag: 'Internal · Client Acquisition',
        year: '2026',
        description:
          'Internal tool I built to land website clients in Puerto Rico. From a Maps search, it audits local businesses, generates a personalized Spanish demo site per lead, and ships the pitch over WhatsApp. Used only by me and my partner, not a SaaS.',
        link: 'https://lupa-seven.vercel.app',
        tech: ['Next.js 16', 'React 19', 'Gemini 3', 'Supabase', 'Stripe'],
        pipeline: ['Maps search', 'AI audit', 'Spanish demo site', 'WhatsApp pitch'],
        metrics: [
          { label: 'Demos generated', value: '120+' },
          { label: 'Categories', value: '7' },
          { label: 'Avg. fixability score', value: '6.4 / 10' },
        ],
        featured: true,
        span: 'wide',
      },
      {
        name: 'demotape',
        media: 'demotape',
        tag: 'Open Source · npm',
        year: '2026',
        description:
          'CLI that records production-quality demo videos of web apps from a JSON config. Auth-aware, skeleton-free, multi-format. Replaces an entire category of $30/mo SaaS tools.',
        link: 'https://github.com/janfaris/demotape',
        tech: ['TypeScript', 'Playwright', 'FFmpeg', 'Zod', 'MIT'],
        pipeline: ['JSON config', 'Headless browser', 'Production video'],
        featured: true,
        span: 'wide',
      },
      {
        name: 'usableai',
        media: 'usableai',
        tag: 'Internal · Content Engine',
        year: '2026',
        description:
          'My private content engine. Runs the @usableai Instagram account: RSS + curated X → GPT-5.5 → vision-QA Spanish carousels, fully automated. Built for me, not for sale.',
        link: 'https://instagram.com/usableai',
        tech: ['Node 22', 'GPT-5.5', 'GPT Image 2', 'Canvas'],
        pipeline: ['RSS + X', 'GPT-5.5', 'Vision QA', 'Instagram'],
      },
      {
        name: 'spanish-tone-spec',
        media: 'spanish-tone-spec',
        tag: 'Open Source · npm',
        year: '2026',
        description:
          'Prompt-side Spanish locale tone control for LLM output. Corpus-driven, no post-hoc regex. Solves the "sounds like Mexico, not PR" problem.',
        link: 'https://www.npmjs.com/package/spanish-tone-spec',
        tech: ['TypeScript', 'Zod', 'MIT'],
      },
      {
        name: 'Vantage',
        media: 'vantage',
        tag: 'Real Estate',
        year: '2025',
        description:
          'AI-powered real estate platform for Puerto Rico: listings, voice search, agent tools.',
        link: 'https://vantagepr.vercel.app',
        tech: ['Next.js', 'Claude', 'ElevenLabs', 'Stripe'],
      },
      {
        name: 'Wandr',
        media: 'wandr',
        tag: 'Travel',
        year: '2025',
        description: 'AI travel planner with itineraries, flights, and local events.',
        link: 'https://wandrtravelai.com',
        tech: ['React', 'Supabase', 'Gemini', 'SerpAPI'],
      },
      {
        name: 'Janga',
        media: 'janga',
        tag: 'iOS App',
        year: '2025',
        description: 'Find where to hang out. Live on the App Store.',
        link: 'https://apps.apple.com/us/app/janga/id6744530407',
        tech: ['Expo', 'React Native', 'Supabase'],
      },
      {
        name: 'Blok',
        media: 'blok',
        span: 'wide',
        tag: 'PropTech',
        year: '2025',
        description: 'AI condo management for Puerto Rico over WhatsApp.',
        link: 'https://www.blokpr.co',
        tech: ['Next.js', 'WhatsApp API', 'Twilio', 'Claude'],
      },
    ],
    experience: [
      {
        company: 'Microsoft',
        role: 'Software Engineer II',
        period: '2025 - 2026',
        note: 'Commerce Core / Compliance Analytics. Shipped PRPilot, an internal Claude-powered PR-review tool that scored 5.0/5.0 on internal AI evaluations across 7+ repos.',
      },
      {
        company: 'Xtillion',
        role: 'Associate Engineer',
        period: '2024 - 2025',
        note: 'Full-stack TypeScript / React / Node for U.S. enterprise clients. Led the Snowflake migration. First taste of real production scale.',
      },
      {
        company: 'Pratt & Whitney',
        role: 'Co-Op Software Engineer',
        period: '2021 - 2023',
        note: 'Two-year co-op writing production code in the aerospace propulsion stack. Learned how shipping under regulation works.',
      },
    ],
    press: [],
    pressEmptyHint:
      'First mentions coming soon. If you write, podcast, or organize on AI / tech in Puerto Rico — I\u2019m happy to talk.',
    now: {
      headline: 'Lupa: my private client-acquisition tool, still pre-launch.',
      lines: [
        'usableai, my private content engine, runs my Spanish AI digest on Instagram. Still polishing.',
        'Writing one essay per month on building AI products from Puerto Rico.',
        'Both tools are in the final polish phase before going wide on real clients.',
      ],
      updated: 'Updated monthly',
    },
    available: {
      headline: {
        lead: 'I’m open to work — ',
        em: 'hire me',
        tail: '.',
      },
      body:
        'I\u2019m looking for my next full-time role, building my own AI products, and taking a small amount of work for founders and teams who want to ship something real. If any of these fit, let\u2019s talk.',
      channels: [
        {
          key: 'hire',
          title: 'Hire me · full-time',
          desc:
            'Founding engineer, staff engineer, or tech lead at AI-native startups. Especially agents, devtools, or LATAM / Spanish-first products.',
          cta: 'Email me',
          href: 'mailto:jankfaris@gmail.com?subject=Full-time%20role',
        },
        {
          key: 'consult',
          title: 'Work with me · project',
          desc:
            'AI audits, build sprints, prompt architecture, or 0→1 product builds. Limited slots per quarter. Best fit: founders shipping for PR / LATAM.',
          cta: 'Book an intro',
          href: 'https://cal.com/janfaris/intro',
        },
        {
          key: 'speak',
          title: 'Talk with me · speaking',
          desc:
            'Talks, panels, podcasts, and workshops on AI in Puerto Rico, Spanish-first products, and shipping with LLMs. Bilingual.',
          cta: 'Pitch a topic',
          href: 'mailto:jankfaris@gmail.com?subject=Speaking%20invite',
        },
      ],
      aside: [
        { key: 'Stack', val: 'TypeScript, Next.js, Python, LLMs, Supabase' },
        { key: 'Domains', val: 'AI agents, devtools, vertical SaaS, LATAM' },
        { key: 'Location', val: 'San Juan, PR · Remote or hybrid SF' },
        { key: 'Languages', val: 'English · Spanish (PR / LATAM register)' },
      ],
    },
    writingCta: 'All writing →',
    allWriting: 'All writing',
    footer: 'Built in Puerto Rico · © 2026 Jan Faris',
  },

  es: {
    meta: {
      title: 'Jan Faris — Productos de IA desde Puerto Rico',
      description:
        'Ingeniero de software construyendo productos de IA en español desde Puerto Rico. Ex-Microsoft. Creador de Lupa, demotape y usableai.',
    },
    nav: {
      en: 'EN',
      es: 'ES',
      work: 'Trabajo',
      writing: 'Ensayos',
      about: 'Experiencia',
      hire: 'Contrátame',
    },
    skipToContent: 'Saltar al contenido',
    mobileDock: { resume: 'Résumé', hire: 'Contrátame' },
    hero: {
      display: {
        lead: 'Software, ',
        em: 'entregado',
        tail: '.',
      },
      lede:
        'Ingeniero de producto de IA para agentes, herramientas de desarrollo y productos pensados primero en español. Ex-Microsoft. Construyo y lanzo de punta a punta.',
      metaItems: [
        { key: 'estado', val: 'disponible · ex-SWE II @ Microsoft' },
        { key: 'lanzados', val: '2 npm, 1 App Store, herramientas internas' },
        { key: 'idiomas', val: 'EN · ES' },
      ],
    },
    workUi: {
      evidence: 'Evidencia del proyecto',
      archiveTitle: 'Más trabajo lanzado',
      archiveBody: 'Productos y experimentos más pequeños, resumidos para recorrerlos rápido.',
      openProject: 'Abrir proyecto',
    },
    proofBar: [
      { value: '08', label: 'productos lanzados' },
      { value: '2 npm · 1 App Store', label: 'lanzamientos públicos' },
      { value: '5.0 / 5.0', label: 'evaluación interna de IA en Microsoft (PRPilot)' },
      { value: '120+', label: 'sitios demo generados por Lupa' },
    ],
    stackProof: [
      {
        claim: 'TypeScript / Node',
        evidence: '2 paquetes npm publicados: demotape y spanish-tone-spec, ambos MIT.',
      },
      {
        claim: 'Sistemas LLM',
        evidence: 'PRPilot obtuvo 5.0/5.0 en evaluaciones internas de IA en Microsoft, en 7+ repos.',
      },
      {
        claim: 'IA en español',
        evidence: 'usableai publica en Instagram a diario: de RSS a carrusel, todo automatizado.',
      },
      {
        claim: 'Producto full-stack',
        evidence: 'Janga disponible en el App Store. Lupa ha generado 120+ sitios demo personalizados.',
      },
      {
        claim: 'Escala de producción',
        evidence: 'Commerce Core en Microsoft. Lideré la migración a Snowflake en Xtillion.',
      },
    ],
    sections: {
      work: 'Trabajo Seleccionado',
      writing: 'Ensayos',
      press: 'Prensa y Charlas',
      now: 'Actualmente Construyendo',
      experience: 'Experiencia',
      proof: 'Stack, Comprobado',
      available: 'Trabaja Conmigo',
      connect: 'Contacto',
    },
    projects: [
      {
        name: 'Lupa',
        media: 'lupa',
        tag: 'IA · Ventas',
        year: '2026',
        description:
          'Descubre negocios locales en Puerto Rico con Gemini 3 + Google Maps, audita sus webs con PageSpeed y genera una página demo personalizada en español para cada lead. Pitch directo por WhatsApp con tracking de vistas.',
        link: 'https://lupa-seven.vercel.app',
        tech: ['Next.js 16', 'React 19', 'Gemini 3', 'Supabase', 'Stripe'],
        pipeline: ['Búsqueda en Maps', 'Auditoría IA', 'Demo en español', 'Pitch por WhatsApp'],
        metrics: [
          { label: 'Demos generados', value: '120+' },
          { label: 'Categorías', value: '7' },
          { label: 'Score de fixability', value: '6.4 / 10' },
        ],
        featured: true,
        span: 'wide',
      },
      {
        name: 'demotape',
        media: 'demotape',
        tag: 'Open Source · npm',
        year: '2026',
        description:
          'CLI que graba videos demo de calidad producción para apps web desde un config en JSON. Maneja autenticación, evita estados de loading, y exporta múltiples formatos. Reemplaza toda una categoría de SaaS de $30/mes.',
        link: 'https://github.com/janfaris/demotape',
        tech: ['TypeScript', 'Playwright', 'FFmpeg', 'Zod', 'MIT'],
        pipeline: ['Config JSON', 'Browser headless', 'Video final'],
        featured: true,
        span: 'wide',
      },
      {
        name: 'usableai',
        media: 'usableai',
        tag: 'Interno · Motor de contenido',
        year: '2026',
        description:
          'Digest diario de IA en español para LATAM. Pipeline automatizado: RSS + X curado → GPT-5.5 → carruseles de Instagram con QA visual.',
        link: 'https://instagram.com/usableai',
        tech: ['Node 22', 'GPT-5.5', 'GPT Image 2', 'Canvas'],
        pipeline: ['RSS + X', 'GPT-5.5', 'QA visual', 'Instagram'],
      },
      {
        name: 'spanish-tone-spec',
        media: 'spanish-tone-spec',
        tag: 'Open Source · npm',
        year: '2026',
        description:
          'Control de tono del español para salida de LLMs, desde el prompt. Basado en corpus, sin regex post-hoc. Resuelve el "suena a México, no a PR".',
        link: 'https://www.npmjs.com/package/spanish-tone-spec',
        tech: ['TypeScript', 'Zod', 'MIT'],
      },
      {
        name: 'Vantage',
        media: 'vantage',
        tag: 'Bienes Raíces',
        year: '2025',
        description:
          'Plataforma de bienes raíces con IA para Puerto Rico: listings, búsqueda por voz, herramientas para agentes.',
        link: 'https://vantagepr.vercel.app',
        tech: ['Next.js', 'Claude', 'ElevenLabs', 'Stripe'],
      },
      {
        name: 'Wandr',
        media: 'wandr',
        tag: 'Viajes',
        year: '2025',
        description: 'Planificador de viajes con IA: itinerarios, vuelos y eventos locales.',
        link: 'https://wandrtravelai.com',
        tech: ['React', 'Supabase', 'Gemini', 'SerpAPI'],
      },
      {
        name: 'Janga',
        media: 'janga',
        tag: 'App iOS',
        year: '2025',
        description: 'Encuentra dónde janguear. Disponible en el App Store.',
        link: 'https://apps.apple.com/us/app/janga/id6744530407',
        tech: ['Expo', 'React Native', 'Supabase'],
      },
      {
        name: 'Blok',
        media: 'blok',
        span: 'wide',
        tag: 'PropTech',
        year: '2025',
        description: 'IA para administración de condominios en Puerto Rico, sobre WhatsApp.',
        link: 'https://www.blokpr.co',
        tech: ['Next.js', 'WhatsApp API', 'Twilio', 'Claude'],
      },
    ],
    experience: [
      {
        company: 'Microsoft',
        role: 'Software Engineer II',
        period: '2025 - 2026',
        note: 'Ingeniería full-time en Microsoft. Sistemas de producción a escala.',
      },
      {
        company: 'Xtillion',
        role: 'Associate Engineer',
        period: '2024 - 2025',
        note: 'Full-stack TypeScript / React / Node para clientes empresariales en EE.UU. Lideré la migración a Snowflake. Primer contacto con escala real.',
      },
      {
        company: 'Pratt & Whitney',
        role: 'Co-Op Software Engineer',
        period: '2021 - 2023',
        note: 'Dos años de co-op escribiendo código de producción para sistemas aeroespaciales.',
      },
    ],
    press: [],
    pressEmptyHint:
      'Primeras menciones próximamente. Si escribes, haces podcasts u organizas eventos sobre IA o tecnología en Puerto Rico — escríbeme.',
    now: {
      headline: 'Lupa: herramienta de ventas con IA para negocios locales en PR.',
      lines: [
        'Publicando diariamente en usableai (digest de IA en español, Instagram).',
        'Escribiendo un ensayo al mes sobre construir productos de IA desde Puerto Rico.',
        'Ambas herramientas están en fase final de pulido antes de salir con clientes reales.',
      ],
      updated: 'Actualizado mensualmente',
    },
    available: {
      headline: {
        lead: 'Estoy disponible — ',
        em: 'contrátame',
        tail: '.',
      },
      body:
        'Estoy buscando mi próximo rol full-time, construyendo mis propios productos de IA, y tomando una pequeña cantidad de trabajo para founders y equipos que quieren lanzar algo real. Si encajas en alguna, hablemos.',
      channels: [
        {
          key: 'hire',
          title: 'Contrátame · full-time',
          desc:
            'Founding engineer, staff engineer o tech lead en startups de IA. Especialmente agentes, devtools, o productos para LATAM / mercados en español.',
          cta: 'Escríbeme',
          href: 'mailto:jankfaris@gmail.com?subject=Rol%20full-time',
        },
        {
          key: 'consult',
          title: 'Proyecto · consultoría',
          desc:
            'Auditorías de IA, sprints de construcción, arquitectura de prompts, o builds 0→1. Cupos limitados por trimestre. Encaja mejor con founders en PR / LATAM.',
          cta: 'Agenda una intro',
          href: 'https://cal.com/janfaris/intro',
        },
        {
          key: 'speak',
          title: 'Charla · speaking',
          desc:
            'Charlas, paneles, podcasts y workshops sobre IA en Puerto Rico, productos en español primero, y cómo lanzar con LLMs. Bilingüe.',
          cta: 'Propón un tema',
          href: 'mailto:jankfaris@gmail.com?subject=Invitación%20a%20hablar',
        },
      ],
      aside: [
        { key: 'Stack', val: 'TypeScript, Next.js, Python, LLMs, Supabase' },
        { key: 'Áreas', val: 'Agentes IA, devtools, vertical SaaS, LATAM' },
        { key: 'Ubicación', val: 'San Juan, PR · Remoto o híbrido SF' },
        { key: 'Idiomas', val: 'Español (registro PR / LATAM) · Inglés' },
      ],
    },
    writingCta: 'Todos los ensayos →',
    allWriting: 'Todos los ensayos',
    footer: 'Hecho en Puerto Rico · © 2026 Jan Faris',
  },
}
