// All site copy in one place. EN + ES.
export type Lang = 'en' | 'es'

export interface Metric { label: string; value: string }
export interface Project {
  name: string
  tag: string
  year: string
  description: string
  link: string
  tech: string[]
  metrics?: Metric[]
  /** Shipped result or actual use, without speculative impact metrics. */
  outcome?: string
  featured?: boolean
  span?: 'wide'
  /** Slug for /demos/<slug>.{mp4,jpg} — when set, card renders an autoplaying muted loop with poster fallback */
  media?: string
  /** Ordered pipeline steps, rendered as a dot-and-line flow diagram in the card. */
  pipeline?: string[]
}
export interface ExperienceItem {
  company: string
  role: string
  period: string
  note: string
  highlights?: string[]
}
export interface PressItem {
  date: string
  outlet: string
  title: string
  link?: string
}

export interface Content {
  meta: {
    title: string
    description: string
  }
  nav: {
    en: string
    es: string
    work: string
    writing: string
    about: string
    hire: string
  }
  skipToContent: string
  mobileDock: { resume: string; hire: string }
  hero: {
    display: { lead: string; em: string; tail: string }
    lede: React.ReactNode | string
    metaItems: { key: string; val: string }[]
  }
  workUi: {
    evidence: string
    outcome: string
    archiveTitle: string
    archiveBody: string
    openProject: string
  }
  /** Hard numbers strip under the hero. */
  proofBar: { value: string; label: string }[]
  sections: {
    work: string
    writing: string
    press: string
    now: string
    experience: string
    available: string
    connect: string
  }
  projects: Project[]
  experience: ExperienceItem[]
  press: PressItem[]
  pressEmptyHint: string
  now: { headline: string; lines: string[]; updated: string }
  available: {
    headline: { lead: string; em: string; tail: string }
    body: string
    channels: {
      key: string
      title: string
      desc: string
      cta: string
      href: string
    }[]
    aside: { key: string; val: string }[]
  }
  readiness: {
    eyebrow: string
    title: string
    body: string
    cta: string
  }
  writingCta: string
  allWriting: string
  footer: string
}

export const content: Record<Lang, Content> = {
  en: {
    meta: {
      title: 'Jan Faris — AI products from Puerto Rico',
      description:
        'Lead AI Engineer at Cencora. Building reliable AI products for healthcare, and independent tools from Puerto Rico. Previously Microsoft.',
    },
    nav: {
      en: 'EN',
      es: 'ES',
      work: 'Work',
      writing: 'Ship Notes',
      about: 'About',
      hire: 'Connect',
    },
    skipToContent: 'Skip to content',
    mobileDock: { resume: 'Résumé', hire: 'Say hello' },
    hero: {
      display: { lead: 'From idea to ', em: 'production', tail: '.' },
      lede:
        'I build AI products that hold up in the real world. Lead AI Engineer at Cencora, working across healthcare, agents, and the path from idea to production.',
      metaItems: [
        { key: 'status', val: 'Lead AI Engineer @ Cencora' },
        { key: 'shipped', val: '2 npm, 1 App Store, internal tools' },
        { key: 'languages', val: 'bilingual · English + Spanish' },
      ],
    },
    workUi: {
      evidence: 'Project evidence',
      outcome: 'In practice',
      archiveTitle: 'More shipped work',
      archiveBody: 'Smaller products and experiments, kept concise for a faster scan.',
      openProject: 'Open project',
    },
    proofBar: [
      { value: '08', label: 'products shipped' },
      { value: '2 npm · 1 App Store', label: 'public launches' },
      { value: '50-100 / wk', label: 'PRs processed by PRPilot' },
      { value: '120+', label: 'demo sites generated by Lupa' },
    ],
    sections: {
      work: 'Selected Work',
      writing: 'Ship Notes',
      press: 'Press & Speaking',
      now: 'Currently Building',
      experience: 'Experience',
      available: 'Good work starts with a conversation.',
      connect: 'Connect',
    },
    projects: [
      {
        name: 'Lupa',
        media: 'lupa',
        tag: 'Internal · Client Acquisition',
        year: '2026',
        description:
          'Turn a weak website into a concrete sales conversation. Lupa audits local businesses, builds a personalized Spanish demo for each lead, and sends the pitch over WhatsApp.',
        outcome: 'Used by me and my partner to pitch local businesses in Puerto Rico. An internal tool, not a public SaaS.',
        link: 'https://lupa-seven.vercel.app',
        tech: ['Next.js 16', 'React 19', 'Gemini 3', 'Supabase', 'Stripe'],
        pipeline: ['Maps search', 'AI audit', 'Spanish demo site', 'WhatsApp pitch'],
        metrics: [
          { label: 'Demos generated', value: '120+' },
          { label: 'Categories', value: '7' },
        ],
        featured: true,
        span: 'wide',
      },
      {
        name: 'demotape',
        media: 'demotape',
        tag: 'Open Source · npm',
        year: '2026',
        description:
          'Recording a new demo should not mean repeating every click by hand. I built a CLI that turns a JSON script into a video, handling login, page readiness, and multiple export formats.',
        outcome: 'Shipped as an MIT-licensed npm package. The recording workflow lives in a reusable config.',
        link: 'https://github.com/janfaris/demotape',
        tech: ['TypeScript', 'Playwright', 'FFmpeg', 'Zod', 'MIT'],
        pipeline: ['JSON config', 'Headless browser', 'Production video'],
        featured: true,
        span: 'wide',
      },
      {
        name: 'usableai',
        media: 'usableai',
        tag: 'Internal · Content Engine',
        year: '2026',
        description:
          'Turns curated AI news into Spanish Instagram carousels with visual QA. The private engine behind @usableai.',
        link: 'https://instagram.com/usableai',
        tech: ['Node 22', 'GPT-5.5', 'GPT Image 2', 'Canvas'],
        pipeline: ['RSS + X', 'GPT-5.5', 'Vision QA', 'Instagram'],
      },
      {
        name: 'spanish-tone-spec',
        media: 'spanish-tone-spec',
        tag: 'Open Source · npm',
        year: '2026',
        description:
          'Helps LLMs write for a specific Spanish-speaking region. Published on npm, with tone controlled in the prompt.',
        link: 'https://www.npmjs.com/package/spanish-tone-spec',
        tech: ['TypeScript', 'Zod', 'MIT'],
      },
      {
        name: 'Vantage',
        media: 'vantage',
        tag: 'Real Estate',
        year: '2025',
        description:
          'Find properties in Puerto Rico by describing them aloud. Voice search, listings, and tools for agents.',
        link: 'https://vantagepr.vercel.app',
        tech: ['Next.js', 'Claude', 'ElevenLabs', 'Stripe'],
      },
      {
        name: 'Wandr',
        media: 'wandr',
        tag: 'Travel',
        year: '2025',
        description: 'Brings itineraries, flights, and local events into one AI-assisted trip plan.',
        link: 'https://wandrtravelai.com',
        tech: ['React', 'Supabase', 'Gemini', 'SerpAPI'],
      },
      {
        name: 'Janga',
        media: 'janga',
        tag: 'iOS App',
        year: '2025',
        description: 'Helps people find where to hang out. Shipped on the App Store.',
        link: 'https://apps.apple.com/us/app/janga/id6744530407',
        tech: ['Expo', 'React Native', 'Supabase'],
      },
      {
        name: 'Blok',
        media: 'blok',
        span: 'wide',
        tag: 'PropTech',
        year: '2025',
        description: 'Brings condo management into WhatsApp, where residents and administrators already communicate.',
        link: 'https://www.blokpr.co',
        tech: ['Next.js', 'WhatsApp API', 'Twilio', 'Claude'],
      },
    ],
    experience: [
      {
        company: 'Cencora',
        role: 'Lead AI Engineer',
        period: 'Aug 2026 - Present',
        note: 'Leading the engineering and production delivery of AI capabilities for healthcare and pharmaceutical supply-chain analytics.',
      },
      {
        company: 'Microsoft',
        role: 'Software Engineer II',
        period: '2025 - 2026',
        note: 'Trust Platform (Commerce Core) · fraud and abuse prevention systems for Microsoft’s commerce ecosystem.',
        highlights: [
          'Built PRPilot, an autonomous AI PR-review agent using Copilot CLI, Microsoft Scout, custom skills, and MCP servers across 7+ repositories.',
          'Maintained compliance-critical transaction-risk APIs serving multiple Microsoft products and countries.',
          'Shipped TypeScript, React, Python, and AKS features from prototype through production.',
          'Co-designed a 21-session org-wide AI program and onboarded roughly 15 PMs to agentic tooling.',
        ],
      },
      {
        company: 'Xtillion',
        role: 'Associate Engineer',
        period: '2024 - 2025',
        note: 'Enterprise healthcare reporting, analytics, and data-platform delivery from system design through operation.',
        highlights: [
          'Led a 12-month migration from SQL Server and SSRS to Retool, Snowflake, dbt, and GitHub Actions — generating 5,000+ reports daily.',
          'Solo-built HIPAA-compliant delivery over encrypted AWS SES email and OpenText Fax API.',
          'Built conversational analytics with Databricks Genie and eliminated an entire SQL Server instance.',
        ],
      },
      {
        company: 'Pratt & Whitney',
        role: 'Software Engineer',
        period: '2021 - 2023',
        note: 'Production software and DevSecOps work in the regulated F-135 aerospace propulsion stack.',
        highlights: [
          'Cut build time 90% by automating and securing CI/CD for the F-135 DevSecOps transformation.',
          'Modernized a legacy database with Perl, Python, and SQL, then built C code-generation and blade-assembly validation tooling.',
        ],
      },
    ],
    press: [],
    pressEmptyHint:
      'First mentions coming soon. If you write, podcast, or organize on AI / tech in Puerto Rico — I\u2019m happy to talk.',
    now: {
      headline: 'Lupa: my private client-acquisition tool, still pre-launch.',
      lines: [
        'usableai, my private content engine, runs my Spanish AI digest on Instagram. Still polishing.',
        'Writing one essay per month on building AI products from Puerto Rico.',
        'Both tools are in the final polish phase before going wide on real clients.',
      ],
      updated: 'Updated monthly',
    },
    available: {
      headline: {
        lead: 'Let’s stay ',
        em: 'connected',
        tail: '.',
      },
      body:
        'My focus is on AI engineering at Cencora and the independent products I build along the way. For conversations about useful AI, open source, or the tech community in Puerto Rico, say hello.',
      channels: [
        {
          key: 'connect',
          title: 'Compare notes',
          desc:
            'Building something with AI? I enjoy exchanging ideas with engineers and product people who care about making it useful.',
          cta: 'Email me',
          href: 'mailto:jankfaris@gmail.com?subject=Let%E2%80%99s%20connect',
        },
        {
          key: 'consult',
          title: 'Build in the open',
          desc:
            'Explore my tools, contribute an idea, or follow what I am building. Small projects, real use cases, and lessons shared along the way.',
          cta: 'Visit GitHub',
          href: 'https://github.com/janfaris',
        },
        {
          key: 'speak',
          title: 'Talk with me · speaking',
          desc:
            'Talks, panels, podcasts, and workshops on AI in Puerto Rico, Spanish-first products, and shipping with LLMs. Bilingual.',
          cta: 'Pitch a topic',
          href: 'mailto:jankfaris@gmail.com?subject=Speaking%20invite',
        },
      ],
      aside: [
        { key: 'Stack', val: 'TypeScript, Next.js, Python, LLMs, Supabase' },
        { key: 'Domains', val: 'AI agents, devtools, vertical SaaS, LATAM' },
        { key: 'Location', val: 'San Juan, Puerto Rico' },
        { key: 'Languages', val: 'English · Spanish (PR / LATAM register)' },
      ],
    },
    readiness: {
      eyebrow: 'Product decision tool · 3 minutes',
      title: 'Should this be AI?',
      body: 'Answer 10 production questions and get a clear recommendation: validate, prototype, pilot, or launch.',
      cta: 'Score your product idea',
    },
    writingCta: 'All Ship Notes →',
    allWriting: 'All Ship Notes',
    footer: 'Built in Puerto Rico · © 2026 Jan Faris',
  },

  es: {
    meta: {
      title: 'Jan Faris — Productos de IA desde Puerto Rico',
      description:
        'Lead AI Engineer en Cencora. Productos de IA confiables para salud y herramientas independientes desde Puerto Rico. Antes en Microsoft.',
    },
    nav: {
      en: 'EN',
      es: 'ES',
      work: 'Trabajo',
      writing: 'Ship Notes',
      about: 'Experiencia',
      hire: 'Hablemos',
    },
    skipToContent: 'Saltar al contenido',
    mobileDock: { resume: 'Résumé', hire: 'Hablemos' },
    hero: {
      display: {
        lead: 'De idea a ',
        em: 'producción',
        tail: '.',
      },
      lede:
        'Construyo productos de IA que funcionan en el mundo real. Lead AI Engineer en Cencora, entre salud, agentes y el camino de idea a producción.',
      metaItems: [
        { key: 'estado', val: 'Lead AI Engineer @ Cencora' },
        { key: 'lanzados', val: '2 npm, 1 App Store, herramientas internas' },
        { key: 'idiomas', val: 'bilingüe · español + inglés' },
      ],
    },
    workUi: {
      evidence: 'Evidencia del proyecto',
      outcome: 'En la práctica',
      archiveTitle: 'Más trabajo lanzado',
      archiveBody: 'Productos y experimentos más pequeños, resumidos para recorrerlos rápido.',
      openProject: 'Abrir proyecto',
    },
    proofBar: [
      { value: '08', label: 'productos lanzados' },
      { value: '2 npm · 1 App Store', label: 'lanzamientos públicos' },
      { value: '50-100 / sem', label: 'PRs procesados por PRPilot' },
      { value: '120+', label: 'sitios demo generados por Lupa' },
    ],
    sections: {
      work: 'Trabajo Seleccionado',
      writing: 'Ship Notes',
      press: 'Prensa y Charlas',
      now: 'Actualmente Construyendo',
      experience: 'Experiencia',
      available: 'Las buenas ideas se conversan.',
      connect: 'Contacto',
    },
    projects: [
      {
        name: 'Lupa',
        media: 'lupa',
        tag: 'IA · Ventas',
        year: '2026',
        description:
          'Convierte una web con problemas en una propuesta concreta. Lupa audita negocios locales, genera una demo personalizada en español para cada prospecto y envía la propuesta por WhatsApp.',
        outcome: 'Mi socio y yo lo usamos para presentar propuestas a negocios locales en Puerto Rico. Es una herramienta interna.',
        link: 'https://lupa-seven.vercel.app',
        tech: ['Next.js 16', 'React 19', 'Gemini 3', 'Supabase', 'Stripe'],
        pipeline: ['Búsqueda en Maps', 'Auditoría IA', 'Demo en español', 'Pitch por WhatsApp'],
        metrics: [
          { label: 'Demos generados', value: '120+' },
          { label: 'Categorías', value: '7' },
        ],
        featured: true,
        span: 'wide',
      },
      {
        name: 'demotape',
        media: 'demotape',
        tag: 'Open Source · npm',
        year: '2026',
        description:
          'Grabar otra demo no debería exigir repetir cada clic a mano. Construí un CLI que convierte un guion JSON en video: maneja el login, espera a que cargue la página y exporta en varios formatos.',
        outcome: 'Publicado en npm bajo licencia MIT. El proceso de grabación queda en una configuración reutilizable.',
        link: 'https://github.com/janfaris/demotape',
        tech: ['TypeScript', 'Playwright', 'FFmpeg', 'Zod', 'MIT'],
        pipeline: ['Config JSON', 'Browser headless', 'Video final'],
        featured: true,
        span: 'wide',
      },
      {
        name: 'usableai',
        media: 'usableai',
        tag: 'Interno · Motor de contenido',
        year: '2026',
        description:
          'Convierte noticias curadas de IA en carruseles en español con QA visual. El motor privado detrás de @usableai.',
        link: 'https://instagram.com/usableai',
        tech: ['Node 22', 'GPT-5.5', 'GPT Image 2', 'Canvas'],
        pipeline: ['RSS + X', 'GPT-5.5', 'QA visual', 'Instagram'],
      },
      {
        name: 'spanish-tone-spec',
        media: 'spanish-tone-spec',
        tag: 'Open Source · npm',
        year: '2026',
        description:
          'Ayuda a los LLMs a escribir para una región hispanohablante específica. Publicado en npm; el tono se controla desde el prompt.',
        link: 'https://www.npmjs.com/package/spanish-tone-spec',
        tech: ['TypeScript', 'Zod', 'MIT'],
      },
      {
        name: 'Vantage',
        media: 'vantage',
        tag: 'Bienes Raíces',
        year: '2025',
        description:
          'Encuentra propiedades en Puerto Rico describiéndolas en voz alta. Búsqueda por voz, listings y herramientas para agentes.',
        link: 'https://vantagepr.vercel.app',
        tech: ['Next.js', 'Claude', 'ElevenLabs', 'Stripe'],
      },
      {
        name: 'Wandr',
        media: 'wandr',
        tag: 'Viajes',
        year: '2025',
        description: 'Reúne itinerarios, vuelos y eventos locales en un plan de viaje asistido por IA.',
        link: 'https://wandrtravelai.com',
        tech: ['React', 'Supabase', 'Gemini', 'SerpAPI'],
      },
      {
        name: 'Janga',
        media: 'janga',
        tag: 'App iOS',
        year: '2025',
        description: 'Ayuda a encontrar dónde janguear. Lanzado en el App Store.',
        link: 'https://apps.apple.com/us/app/janga/id6744530407',
        tech: ['Expo', 'React Native', 'Supabase'],
      },
      {
        name: 'Blok',
        media: 'blok',
        span: 'wide',
        tag: 'PropTech',
        year: '2025',
        description: 'Lleva la administración del condominio a WhatsApp, donde ya se comunican residentes y administradores.',
        link: 'https://www.blokpr.co',
        tech: ['Next.js', 'WhatsApp API', 'Twilio', 'Claude'],
      },
    ],
    experience: [
      {
        company: 'Cencora',
        role: 'Lead AI Engineer',
        period: 'Ago 2026 - Presente',
        note: 'Liderando la ingeniería y la puesta en producción de capacidades de IA para salud y analítica de la cadena de suministro farmacéutica.',
      },
      {
        company: 'Microsoft',
        role: 'Software Engineer II',
        period: '2025 - 2026',
        note: 'Trust Platform (Commerce Core) · sistemas de prevención de fraude y abuso para el ecosistema de comercio de Microsoft.',
        highlights: [
          'Construí PRPilot, un agente autónomo para revisar PRs con Copilot CLI, Microsoft Scout, skills y servidores MCP en 7+ repositorios.',
          'Mantuve APIs críticas de riesgo transaccional para múltiples productos y países.',
          'Llevé features en TypeScript, React, Python y AKS de prototipo a producción.',
          'Co-diseñé un programa de IA de 21 sesiones y capacité a unos 15 PMs en tooling agéntico.',
        ],
      },
      {
        company: 'Xtillion',
        role: 'Associate Engineer',
        period: '2024 - 2025',
        note: 'Entrega end-to-end de reportes de salud, analytics y plataformas de datos empresariales.',
        highlights: [
          'Lideré una migración de 12 meses de SQL Server y SSRS a Retool, Snowflake, dbt y GitHub Actions — generando 5,000+ reportes diarios.',
          'Construí solo la entrega HIPAA-compliant por AWS SES y OpenText Fax API.',
          'Desarrollé analytics conversacional con Databricks Genie y eliminé una instancia completa de SQL Server.',
        ],
      },
      {
        company: 'Pratt & Whitney',
        role: 'Software Engineer',
        period: '2021 - 2023',
        note: 'Software de producción y DevSecOps para la plataforma regulada de propulsión aeroespacial F-135.',
        highlights: [
          'Reduje el build time 90% automatizando y asegurando CI/CD para la transformación DevSecOps del F-135.',
          'Modernicé una base de datos legacy con Perl, Python y SQL, y construí tooling de generación en C y validación de ensamblaje.',
        ],
      },
    ],
    press: [],
    pressEmptyHint:
      'Primeras menciones próximamente. Si escribes, haces podcasts u organizas eventos sobre IA o tecnología en Puerto Rico — escríbeme.',
    now: {
      headline: 'Lupa: herramienta de ventas con IA para negocios locales en PR.',
      lines: [
        'Publicando diariamente en usableai (digest de IA en español, Instagram).',
        'Escribiendo un ensayo al mes sobre construir productos de IA desde Puerto Rico.',
        'Ambas herramientas están en fase final de pulido antes de salir con clientes reales.',
      ],
      updated: 'Actualizado mensualmente',
    },
    available: {
      headline: {
        lead: 'Sigamos ',
        em: 'conectados',
        tail: '.',
      },
      body:
        'Mi enfoque está en ingeniería de IA en Cencora y en los productos independientes que sigo construyendo. Para conversar sobre IA útil, open source o la comunidad tech de Puerto Rico, escríbeme.',
      channels: [
        {
          key: 'connect',
          title: 'Intercambiemos ideas',
          desc:
            '¿Estás construyendo con IA? Me gusta intercambiar ideas con gente de ingeniería y producto que quiere hacerla útil.',
          cta: 'Escríbeme',
          href: 'mailto:jankfaris@gmail.com?subject=Conversemos',
        },
        {
          key: 'consult',
          title: 'Construir en comunidad',
          desc:
            'Explora mis herramientas, aporta una idea o sigue lo que construyo. Proyectos pequeños, casos reales y lecciones compartidas.',
          cta: 'Visita GitHub',
          href: 'https://github.com/janfaris',
        },
        {
          key: 'speak',
          title: 'Charla · speaking',
          desc:
            'Charlas, paneles, podcasts y workshops sobre IA en Puerto Rico, productos en español primero, y cómo lanzar con LLMs. Bilingüe.',
          cta: 'Propón un tema',
          href: 'mailto:jankfaris@gmail.com?subject=Invitación%20a%20hablar',
        },
      ],
      aside: [
        { key: 'Stack', val: 'TypeScript, Next.js, Python, LLMs, Supabase' },
        { key: 'Áreas', val: 'Agentes IA, devtools, vertical SaaS, LATAM' },
        { key: 'Ubicación', val: 'San Juan, Puerto Rico' },
        { key: 'Idiomas', val: 'Español (registro PR / LATAM) · Inglés' },
      ],
    },
    readiness: {
      eyebrow: 'Herramienta de decisión · 3 minutos',
      title: '¿Esto debería usar IA?',
      body: 'Contesta 10 preguntas de producción y recibe una recomendación clara: valida, prototipa, haz un piloto o lanza.',
      cta: 'Evalúa tu idea de producto',
    },
    writingCta: 'Todas las Ship Notes →',
    allWriting: 'Todas las Ship Notes',
    footer: 'Hecho en Puerto Rico · © 2026 Jan Faris',
  },
}
